- name: Guacamole Dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - build-essential 
      - freerdp-x11
      - g++-6
      - gcc-6
      - ghostscript
      - haveged
      - jq
      - libavcodec-dev
      - libavutil-dev
      - libcairo2-dev
      - libfreerdp-dev
      - libjpeg-turbo8-dev
      - libossp-uuid-dev
      - libpango1.0-dev
      - libpng-dev
      - libpulse-dev
      - libssh2-1-dev
      - libssl-dev
      - libswscale-dev
      - libtelnet-dev
      - libvncserver-dev
      - libvorbis-dev
      - libwebp-dev
      - tomcat8
      - tomcat8-admin
      - tomcat8-common
      - tomcat8-user

- name: Stop Tomcat Service
  systemd:
    name: tomcat8
    state: stopped

- name: Download Guacamole Client
  get_url:
    url: 'http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/0.9.14/binary/guacamole-0.9.14.war'
    dest: '/var/lib/tomcat8/webapps/guacamole.war'

- name: Download Guacamole Server
  get_url:
    url: 'http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/0.9.14/source/guacamole-server-0.9.14.tar.gz'
    dest: '{{ source_dir }}/guacamole-server-0.9.14.tar.gz'

- name: Unarchive Guacamole Server
  unarchive:
    src: '{{ source_dir }}/guacamole-server-0.9.14.tar.gz'
    dest: '{{ software_dir }}'
    creates: '{{ software_dir }}/guacamole-server-0.9.14'
    remote_src: yes

- name: Create Guacamole mysql DB
  mysql_db:
    name: guac_db
    encoding: utf8
    state: present
    login_user: 'root'
    login_password: '{{ mysql_root_pass }}'

- name: Create Guacamole mysql User
  mysql_user:
    name: guac_user
    password: guacdungeon
    priv: guac_db.*:ALL,GRANT
    state: present
    login_user: 'root'
    login_password: '{{ mysql_root_pass }}'

- name: Configure Guacamole Server
  command: './configure cc=gcc-6 --with-init-dir=/etc/init.d'
  args:
    chdir: '{{ software_dir }}/guacamole-server-0.9.14'

- name: Make Guacamole Server
  command: 'make CC=gcc-6'
  args:
    chdir: '{{ software_dir }}/guacamole-server-0.9.14'

- name: Make Install Guacamole Server
  command: 'make install'
  args:
    chdir: '{{ software_dir }}/guacamole-server-0.9.14'

- name: Update ldconfig for Guacamole Server
  command: 'ldconfig'

- name: Download Guacamole JDBC
  get_url:
    url: 'http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/0.9.14/binary/guacamole-auth-jdbc-0.9.14.tar.gz'
    dest: '{{ source_dir }}/guacamole-auth-jdbc-0.9.14.tar.gz'

- name: Unarchive Guacamole JDBC
  unarchive:
    src: '{{ source_dir }}/guacamole-auth-jdbc-0.9.14.tar.gz'
    dest: '{{ software_dir }}'
    creates: '{{ software_dir }}/guacamole-auth-jdbc-0.9.14'
    remote_src: yes

- name: Make Relevant Dirs
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - /etc/guacamole
    - /etc/guacamole/lib
    - /etc/guacamole/extensions

- name: Copy Guacamole JDBC
  file:
    src: '{{ software_dir }}/guacamole-auth-jdbc-0.9.14/mysql/guacamole-auth-jdbc-mysql-0.9.14.jar'
    dest: /etc/guacamole/extensions
    state: hard

- name: Start and Enable Guacamole Server
  systemd:
    name: guacd
    state: started
    enabled: yes

- name: Restart Tomcat8
  systemd:
    name: tomcat8
    state: restarted
    enabled: yes