# Install a lot of dependencies
- name: Guacamole Dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - build-essential 
      - freerdp-x11
      - g++-6
      - gcc-6
      - ghostscript
      - haveged
      - jq
      - libavcodec-dev
      - libavutil-dev
      - libcairo2-dev
      - libfreerdp-dev
      - libjpeg-turbo8-dev
      #- libmysql-java
      - libossp-uuid-dev
      - libpango1.0-dev
      - libpng-dev
      - libpulse-dev
      - libssh2-1-dev
      - libssl-dev
      - libswscale-dev
      - libtelnet-dev
      - libvncserver-dev
      - libvorbis-dev
      - libwebp-dev
      - tomcat8
      - tomcat8-admin
      - tomcat8-common
      - tomcat8-user

# Stop the Tomcat service to make changes
- name: Stop Tomcat Service
  systemd:
    name: tomcat8
    state: stopped

# Download the Client 'war' package and put it in tomcat
- name: Download Guacamole Client
  get_url:
    url: 'http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/0.9.14/binary/guacamole-0.9.14.war'
    dest: '/var/lib/tomcat8/webapps/guacamole.war'

# Download Server
- name: Download Guacamole Server
  get_url:
    url: 'http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/0.9.14/source/guacamole-server-0.9.14.tar.gz'
    dest: '{{ source_dir }}/guacamole-server-0.9.14.tar.gz'

# Unzip server
- name: Unarchive Guacamole Server
  unarchive:
    src: '{{ source_dir }}/guacamole-server-0.9.14.tar.gz'
    dest: '{{ software_dir }}'
    creates: '{{ software_dir }}/guacamole-server-0.9.14'
    remote_src: yes

# Create a Guacamole MySQL DB
#- name: Create Guacamole mysql DB
#  mysql_db:
#    name: guac_db
#    encoding: utf8
#    state: present
#    login_user: 'root'
#    login_password: '{{ mysql_root_pass }}'

# Create a Guacamole MySQL User, using our root account
#- name: Create Guacamole mysql User
#  mysql_user:
#    name: guac_user
#    password: guacdungeon
#    priv: guac_db.*:ALL,GRANT
#    state: present
#    login_user: 'root'
#    login_password: '{{ mysql_root_pass }}'

# Configure the server, using GCC-6
- name: Configure Guacamole Server
  command: './configure cc=gcc-6 --with-init-dir=/etc/init.d'
  args:
    chdir: '{{ software_dir }}/guacamole-server-0.9.14'

# Make the server, using GCC-6
- name: Make Guacamole Server
  command: 'make CC=gcc-6'
  args:
    chdir: '{{ software_dir }}/guacamole-server-0.9.14'

# make install server
- name: Make Install Guacamole Server
  command: 'make install'
  args:
    chdir: '{{ software_dir }}/guacamole-server-0.9.14'

# refresh the LD
- name: Update ldconfig for Guacamole Server
  command: 'ldconfig'

# We need a Java DB Connector for Guacamole
#- name: Download Guacamole JDBC
#  get_url:
#    url: 'http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/0.9.14/binary/guacamole-auth-jdbc-0.9.14.tar.gz'
#    dest: '{{ source_dir }}/guacamole-auth-jdbc-0.9.14.tar.gz'

# Unzip it
#- name: Unarchive Guacamole JDBC
#  unarchive:
#    src: '{{ source_dir }}/guacamole-auth-jdbc-0.9.14.tar.gz'
#    dest: '{{ software_dir }}'
#    creates: '{{ software_dir }}/guacamole-auth-jdbc-0.9.14'
#    remote_src: yes

# Import the Java DB Connector Guacamole DB Shemas
#- name: Import Guacamole mysql Database Schemas
#  mysql_db:
#    state: import
#    name: guac_db
#    login_user: guac_user
#    login_password: guacdungeon
#    target: '{{ item }}'
#  loop:
#    - '{{ software_dir }}/guacamole-auth-jdbc-0.9.14/mysql/schema/001-create-schema.sql'
#    - '{{ software_dir }}/guacamole-auth-jdbc-0.9.14/mysql/schema/002-create-admin-user.sql'
#  ignore_errors: yes

# Make a bunch of directories that will be needed
- name: Make Relevant Dirs
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - /etc/guacamole
#    - /etc/guacamole/lib
#    - /etc/guacamole/extensions

# Copy the Java DB Connector jar to the Guacamole extensions dir
#- name: Copy Guacamole JDBC
#  file:
#    src: '{{ software_dir }}/guacamole-auth-jdbc-0.9.14/mysql/guacamole-auth-jdbc-mysql-0.9.14.jar'
#    dest: /etc/guacamole/extensions
#    state: hard

# We also need a Java DB mysql Connector
#- name: Get Java DB Connector
#  get_url:
#    url: 'https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java_8.0.11-1ubuntu18.04_all.deb'
#    dest: '{{ source_dir }}/mysql-connector-java_8.0.11-1ubuntu18.04_all.deb'

# This needs to be installed
#- name: Install Java DB Connector
#  apt:
#    deb: '{{ source_dir }}/mysql-connector-java_8.0.11-1ubuntu18.04_all.deb'

# and then symlinked to the Guacamole lib dir
#- name: Symlink Java DB Connector to Guacamole
#  file:
#    src: '/usr/share/java/mysql-connector-java-8.0.11.jar'
#    dest: '/etc/guacamole/lib/mysql-connector-java.jar'
#    state: link

# create guacamole.properties to tell it where the mysql db is
#- name: Create guacamole.properties
#  copy:
#    dest: /etc/guacamole/guacamole.properties
#    content: |
#      mysql-hostname: localhost
#      mysql-port: 3306
#      mysql-database: guac_db
#      mysql-username: guac_user
#      mysql-password: guacdungeon

# create user-mapping.xml
- name: Create user-mapping.xml
  copy:
    dest: /etc/guacamole/user-mapping.xml
    content: |
      <user-mapping>
      <authorize username="guac_user" password="guacdungeon">
      <connection name="Terminal">
      <protocol>ssh</protocol>
      <param name="hostname">localhost</param>
      <param name="port">22</param>
      <param name="username">master</param>
      <param name="password">meatdungeon</param>
      </connection>
      <connection name="Desktop">
      <protocol>rdp</protocol>
      <param name="hostname">localhost</param>
      <param name="port">3389</param>
      <param name="username">master</param>
      <param name="password">meatdungeon</param>
      </connection>
      </authorize>
      </user-mapping>

- name: Start and Enable Guacamole Server
  systemd:
    name: guacd
    state: started
    enabled: yes

- name: Restart Tomcat8
  systemd:
    name: tomcat8
    state: restarted
    enabled: yes