# Install a lot of dependencies
- name: Guacamole Dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - build-essential 
      - freerdp-x11
      - g++-6
      - gcc-6
      - ghostscript
      - haveged
      - jq
      - libavcodec-dev
      - libavutil-dev
      - libcairo2-dev
      - libfreerdp-dev
      - libjpeg-turbo8-dev
      - libossp-uuid-dev
      - libpango1.0-dev
      - libpng-dev
      - libpulse-dev
      - libssh2-1-dev
      - libssl-dev
      - libswscale-dev
      - libtelnet-dev
      - libvncserver-dev
      - libvorbis-dev
      - libwebp-dev
      - tomcat8
      - tomcat8-admin
      - tomcat8-common
      - tomcat8-user

# Stop the Tomcat service to make changes
- name: Stop Tomcat Service
  systemd:
    name: tomcat8
    state: stopped

# Download the Client 'war' package and put it in tomcat
- name: Download Guacamole Client
  get_url:
    url: 'http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/0.9.14/binary/guacamole-0.9.14.war'
    dest: '/var/lib/tomcat8/webapps/guacamole.war'

# Download Server
- name: Download Guacamole Server
  get_url:
    url: 'http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/0.9.14/source/guacamole-server-0.9.14.tar.gz'
    dest: '{{ source_dir }}/guacamole-server-0.9.14.tar.gz'

# Unzip server
- name: Unarchive Guacamole Server
  unarchive:
    src: '{{ source_dir }}/guacamole-server-0.9.14.tar.gz'
    dest: '{{ software_dir }}'
    creates: '{{ software_dir }}/guacamole-server-0.9.14'
    remote_src: yes

# Configure the server, using GCC-6
- name: Configure Guacamole Server
  command: './configure cc=gcc-6 --with-init-dir=/etc/init.d'
  args:
    chdir: '{{ software_dir }}/guacamole-server-0.9.14'

# Make the server, using GCC-6
- name: Make Guacamole Server
  command: 'make CC=gcc-6'
  args:
    chdir: '{{ software_dir }}/guacamole-server-0.9.14'

# make install server
- name: Make Install Guacamole Server
  command: 'make install'
  args:
    chdir: '{{ software_dir }}/guacamole-server-0.9.14'

# refresh the LD
- name: Update ldconfig for Guacamole Server
  command: 'ldconfig'

# Make a bunch of directories that will be needed
- name: Make Relevant Dirs
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - /etc/guacamole

# create user-mapping.xml
- name: Create user-mapping.xml
  copy:
    dest: /etc/guacamole/user-mapping.xml
    content: |
      <user-mapping>
      <authorize username="master" password="test">
      <connection name="Terminal">
      <protocol>ssh</protocol>
      <param name="hostname">localhost</param>
      <param name="port">22</param>
      <param name="username">master</param>
      <param name="color-scheme">green-black</param>
      <param name="enable-sftp">true</param>
      </connection>
      <connection name="Desktop">
      <protocol>rdp</protocol>
      <param name="hostname">localhost</param>
      <param name="port">3389</param>
      <param name="username">master</param>
      <param name="password">meatdungeon</param>
      <param name="resize-method">display-update</param>
      <param name="enable-sftp">true</param>
      <param name="enable-wallpaper">true</param>
      </connection>
      </authorize>
      </user-mapping>

- name: Start and Enable Guacamole Server
  systemd:
    name: guacd
    state: started
    enabled: yes

- name: Restart Tomcat8
  systemd:
    name: tomcat8
    state: restarted
    enabled: yes