# Setup mariadb root Password
- name: Set mariadb root password before installing
  debconf:
    name: 'mariadb-server'
    question: 'mariadb-server/root_password'
    value: '{{mysql_root_pass | quote}}'
    vtype: 'password'

- name: Confirm mariadb root password before installing
  debconf:
    name: 'mariadb-server'
    question: 'mariadb-server/root_password_again'
    value: '{{mysql_root_pass | quote}}'
    vtype: 'password'

- name: Installing MySQL python/php
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - python-mysqldb
    - php-mysql

- name: Installing mariadb Server
  apt:
    name: mariadb-server
    state: present
  
- name: Installing mariadb Client
  apt:
    name: mariadb-common
    state: present
 
# Final MySQL Setup
- name: Ensure Anonymous Users are not in the Database
  mysql_user:
    name: ''
    host: localhost
    state: absent

- name: Secure the MySQL root User
  mysql_user:
    name: root
    password: "{{ mysql_root_pass }}"
    encrypted: yes
    priv: '*.*:ALL'
    host: "{{ item }}"
    host_all: yes
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    state: present
  loop:
    - 127.0.0.1
    - localhost
    - ::1

- name: Remove the Test Database
  mysql_db:
    name: test
    state: absent
