- name: Installing XRDP
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: yes
    update_cache: yes
  vars:
    packages:
      - xrdp
      - xorgxrdp

- name: Enable XRDP
  systemd:
    name: xrdp
    enabled: yes