- name: Installing XRDP
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: yes
    update_cache: yes
  var:
    packages:
      - xrdp
      - xorgxrdp

- name: Enable XRDP
  systemd:
    name: xrdp
    enabled: yes

# - name: Configure XRDP with MATE
# sudo sed -i.bak '/fi/a #xrdp multiple users configuration \n mate-session \n' /etc/xrdp/startwm.sh