- hosts: all
  become: yes
  vars:
    - workshop_user: genomics
    - workshop_user_password: '$6$PllDTv0UD$4DmrifwT2tO/Ve.QF1EpWMf17QAtmjz9hcV/s/S71O8rXf3Yyd4ZIWCkelkQNCG6D0bsAkl9/YBSD87cBSfgS1'
    - workshop_user_password_md5: 3d7d6d2c98be10d5bea507fe383604b9
    - software_dir: "/home/{{workshop_user}}/software"
    - source_dir: "/home/{{workshop_user}}/software/.source"
    - workshop_dir: "/home/{{workshop_user}}/workshop_materials"

  pre_tasks:
    - name: Create {{workshop_user}} Workshop User
      user:
        name: '{{ workshop_user }}'
        group: workshop
        comment: '{{ workshop_user }} Workshop User'
        state: present
        shell: /bin/bash
        password: '{{ workshop_user_password }}'
      tags: user

    - name: Create Software Dir
      file:
        path: '{{ software_dir }}'
        state: directory
        owner: '{{ workshop_user }}'
        group: workshop

    - name: Create Software Source Dir
      file:
        path: '{{ source_dir }}'
        state: directory
        owner: '{{ workshop_user }}'
        group: workshop

    - name: Create Workshop Directory
      file:
        path: '{{ workshop_dir }}'
        state: directory
        owner: '{{ workshop_user }}'
        group: workshop

    - name: Profile Info
      include: software_tasks/profile.yaml
      tags: alias, profile
    
    - name: Changing hostname to {{ workshop_user }}
      lineinfile: dest=/etc/hostname regexp="^ip.*" line="{{workshop_user}}"
      tags: hostname

    - name: Changing hosts to {{ workshop_user }}
      lineinfile: dest=/etc/hosts regexp="^127.*" line="127.0.0.1 localhost {{workshop_user}}"
      tags: hostname

    - name: Hostname
      include: software_tasks/hostname.yaml
      tags: hostname

    - name: Message of the Day
      include: software_tasks/motd.yaml
      tags: motd

    - name: Desktop
      include: software_tasks/desktop.yaml
      tags: desktop

    - name: Guacamole {{ workshop_user }}
      include: software_tasks/guacamole_user.yaml
      tags: guacamole

  tasks:
    # shared
    - name: Installing BioPerl
      cpanm:
        name: CJFIELDS/BioPerl-1.007001.tar.gz
      tags: general, alignment, assembly, genomics, qc, bioperl

    - name: Installing BioPython
      pip:
        name: biopython
        state: present
      tags: general, alignment, assembly, genomics, qc, biopython

    - name: Installing bamtools
      apt:
        name: '{{ packages }}'
        state: present
      vars:
        packages:
          - bamtools
          - libbamtools-dev
          - libbamtools2.4.0
          - pbbamtools
          - sra-toolkit
      tags: general, alignment, assembly, genomics, qc, transcriptomics

    - name: Conda 3.0
      include: software_tasks/conda.yaml version=3 prefix=/home/genomics/miniconda
      tags: general, condax`qiime2_env

    - name: Bioconda
      include: software_tasks/bioconda.yaml version=3 prefix=/home/genomics/miniconda
      tags: general, conda, bioconda, qiime, qiime2

    # unix - none/standard
    # intro R - standard?
    - name: Installing littler
      apt:
        name: '{{ packages }}'
        state: present
      vars:
        packages:
          - r-cran-littler
          - littler
      tags: r, littler, r_introduction, statistics

    - name: Installing LaTeX & pandoc
      apt:
        name: '{{ packages }}'
        state: present
      vars:
        packages:
          - texlive-full
          - texlive-science
          - pandoc
      tags: r, r_introduction, statistics

    - name: R Libraries
      include: software_tasks/r_introduction.yaml
      become: yes
      tags: r, r_introduction, statistics

    # QC
    - name: FastQC
      include: software_tasks/fastqc.yaml version=0.11.8
      tags: fastqc, qc

    - name: Installing Cutadapt
      pip:
        name: cutadapt
        state: present
      tags: cutadapt, qc

    - name: Trim Galore
      include: software_tasks/trim_galore.yaml version=0.5.0
      tags: trim_galore, qc

    - name: BBMap
      include: software_tasks/bbmap.yaml version=38.34
      tags: bbmap, qc

    # alignment
    - name: minimap2
      include: software_tasks/minimap2.yaml
      tags: minimap, alignment

    # genomics
    - name: Install trimmomatic
      apt:
        name: '{{ packages }}'
        state: present
      vars:
        packages:
          - trimmomatic
      tags: genomics, trimmomatic

    - name: fastq-mcf
      include: software_tasks/ea_utils.yaml
      tags: genomics, fastq-mcf, ea_utils

    - name: BWA
      include: software_tasks/bwa.yaml
      tags: genomics, bwa

    - name: Samtools
      include: software_tasks/samtools.yaml version=1.9
      tags: genomics, samtools

    - name: Qualimap
      include: software_tasks/qualimap.yaml version=2.2.1
      tags: genomics, qualimap

    - main: IGV
      include: software_tasks/igv.yaml major_version=2.4 full_version=2.4.16
      tags: genomics, igv

    - main: IGV Tools
      include: software_tasks/igvtools.yaml major_version=2.4 full_version=2.4.16
      tags: genomics, igvtools

    - main: BCFTools
      include: software_tasks/bcftools.yaml version=1.9
      tags: genomics, bcftools

    - name: Installing vcftools
      apt:
        name: vcftools
        state: present
      tags: genomics, vcftools

    - name: Install bedtools
      apt:
        name: bedtools
        state: present
      tags: genomics, bedtools

    - name: bam2fastq
      include: software_tasks/bam2fastq.yaml version=1.1.0
      tags: genomics, bam2fastq

    - main: SPAdes
      include: software_tasks/SPAdes.yaml version=3.13.0
      tags: genomics, spades

    - name: QUAST
      include: software_tasks/quast.yaml version=5.0.2
      tags: assembly, genomics, quast

    - name: Installing EMBOSS tools (getorf)
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - emboss
        - emboss-data
        - emboss-doc
        - emboss-lib
        - jemboss
      tags: genomics, emboss, getorf

    - name: Installing blast legacy & blast+
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - ncbi-blast+
        - ncbi-blast+-legacy
        - ncbi-tools-bin
        - ncbi-tools-x11
      tags: genomics, blast

    - name: Other genomics scripts
      include: software_tasks/genomics_tutorial_extras.yaml
      tags: genomics, genomics_extras

    # assembly - waiting
    # reproducible - waiting
    # visualisation - R/bioconductor libs
    - name: R Libraries
      include: software_tasks/r_visualisation.yaml
      become: yes
      tags: r, visualisation

    # statistics - waiting
    ## I put most of this in R Intro

    # transcriptomics - usually github
    - include: software_tasks/trinity.yaml
      tags: trinity, transcriptomics

    - include: software_tasks/trinotate.yaml
      tags: transcriptomics, trinotate, transdecoder      

    - include: software_tasks/cbs_programs.yaml
      tags: trinity, cbs, signalp, tmhmm, rnammer, transcriptomics

    # microbiome
    - name: QIIME2
      include: software_tasks/qiime2_env.yaml
      tags: qiime, qiime2

    # stacks - waiting
    - include: software_tasks/stacks.yaml version=2.2
      tags: radseq, stacks

    # phylogenomics - waiting