- hosts: all
  become: yes
  vars:
    - workshop_user: genomics
    - workshop_user_password: '$6$PllDTv0UD$4DmrifwT2tO/Ve.QF1EpWMf17QAtmjz9hcV/s/S71O8rXf3Yyd4ZIWCkelkQNCG6D0bsAkl9/YBSD87cBSfgS1'
    - workshop_user_password_md5: 3d7d6d2c98be10d5bea507fe383604b9
    - software_dir: "/home/{{workshop_user}}/software"
    - source_dir: "/home/{{workshop_user}}/software/.source"
    - workshop_dir: "/home/{{workshop_user}}/workshop_materials"

  pre_tasks:
    - name: Create {{workshop_user}} Workshop User
      user:
        name: '{{ workshop_user }}'
        group: workshop
        comment: '{{ workshop_user }} Workshop User'
        state: present
        shell: /bin/bash
        password: '{{ workshop_user_password }}'
      tags: user

    - name: Create Software Dir
      file:
        path: '{{ software_dir }}'
        state: directory
        owner: '{{ workshop_user }}'
        group: workshop

    - name: Create Software Source Dir
      file:
        path: '{{ source_dir }}'
        state: directory
        owner: '{{ workshop_user }}'
        group: workshop

    - name: Create Workshop Directory
      file:
        path: '{{ workshop_dir }}'
        state: directory
        owner: '{{ workshop_user }}'
        group: workshop

    - name: Profile Info
      include: software_tasks/profile.yaml
      tags: alias, profile
    
    - name: Changing hostname to {{ workshop_user }}
      lineinfile: dest=/etc/hostname regexp="^ip.*" line="{{workshop_user}}"
      tags: hostname

    - name: Changing hosts to {{ workshop_user }}
      lineinfile: dest=/etc/hosts regexp="^127.*" line="127.0.0.1 localhost {{workshop_user}}"
      tags: hostname

    - name: Hostname
      include: software_tasks/hostname.yaml
      tags: hostname

    - name: Message of the Day
      include: software_tasks/motd.yaml
      tags: motd

    - name: Desktop
      include: software_tasks/desktop.yaml
      tags: desktop

    - name: Guacamole {{ workshop_user }}
      include: software_tasks/guacamole_user.yaml
      tags: guacamole

  tasks:
    # shared
    - name: Installing BioPerl
      cpanm:
        name: CJFIELDS/BioPerl-1.007001.tar.gz
      tags: general, alignment, assembly, genomics, seqdqc, bioperl

    - name: Installing BioPython
      pip:
        name: biopython
        state: present
      tags: general, alignment, assembly, genomics, seqdqc, biopython

    - name: Installing bamtools
      apt:
        name: '{{ packages }}'
        state: present
      vars:
        packages:
          - bamtools
          - libbamtools-dev
          - libbamtools2.4.0
          - pbbamtools
          - sra-toolkit
      tags: general, alignment, assembly, genomics, seqdqc, transcriptomics

    - name: Conda 3.0
      include: software_tasks/conda.yaml version=3 prefix=/home/genomics/miniconda
      tags: general, conda, qiime, qiime2

    - name: Bioconda
      include: software_tasks/bioconda.yaml version=3 prefix=/home/genomics/miniconda
      tags: general, conda, bioconda, qiime, qiime2

    # unix
    # intro R

    # QC
    - name: FastQC
      include: software_tasks/fastqc.yaml version=0.11.8
      tags: fastqc, qc

    - name: Installing Cutadapt
      pip:
        name: cutadapt
        state: present
      tags: cutadapt, qc

    - name: Trim Galore
      include: software_tasks/trim_galore.yaml version=0.5.0
      tags: trim_galore, qc

    - name: BBMap
      include: software_tasks/bbmap.yaml version=38.34
      tags: bbmap, qc

    # alignment
    - name: minimap2
      include: software_tasks/minimap2.yaml
      tags: minimap, alignment

    # genomics
    # assembly
    # reproducible
    # visualisation
    # statistics
    # transcriptomics
    # microbiome

    # stacks
    # phylogenomics