- hosts: all
  become: yes
  vars:
    - software_dir: /home/ubuntu/software
    - source_dir: "{{software_dir}}/.source"
    - mysql_root_pass: '*522F526859693BE4EBF948CA2FC0A25326CFD84E'
    - master_password: '$6$vaUtdo8oSgvGmBNO$B/0gxyOCv5b1DWGaiOTBUdZdHW5nrXZhUNw1yu8pVL5LS8Hs3DxL3/rD0aBEx9h7kNpDi73UZ3XYd7wpbXAx90'
    - guac_password: '$6$0TEVj4vBasQhOu$R2fGSbdzZc2qSnpSCJNJiyotnhbz6HWZdLAwb5Ma7M/F4X9BElTeTU/Nn13s/yOf9N1VkuVNwHqNV2FGMj.9A1'

  pre_tasks:
    # create Directories
    - name: Create Software Dir
      file: path={{software_dir}} state=directory
    - name: Create Software Source Dir
      file: path={{source_dir}} state=directory

    # setup workhsop group  
    - name: Create Workshop Group
      group: name=workshop state=present

    # setup a master user with the above SHA-512 crypted password using mkpasswd
    - name: Create 'master' Workshop User with SUDO privileges
      user: name=master group=workshop comment="Master Workshop User" state=present shell=/bin/bash groups="workshop,sudo" password="{{master_password}}"
    
    # We don't be use security keys in the workshop, so password-only logins need to be enabled.
    - name: Enable Password Login
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication yes"
   
    # Amazon has a keep alive around 60 seconds, then the ssh session times out. That's annoying, let's keep it alive!
    - name: Changing SSH Timeout
      lineinfile: dest=/etc/ssh/sshd_config line="ClientAliveInterval 60"

    # Restart the SSH Daemon for the above changes to take effect.
    - name: Restart SSH Daemon
      service: name=ssh state=restarted

  tasks:
    # Install MATE Desktop Environment and remove Overlay Scroll
    - name: Install MATE Desktop
      apt:
        name: "{{ packages }}"
        state: present
        install_recommends: yes
      vars:
        packages:
          - mate-core
          - mate-desktop-environment
          - mate-desktop-environment-extras
      tags: mate

    - name: Disable Scroll Overlay
      apt: name=overlay-scrollbar state=absent purge=yes
      tags: overlay

    - name: Remove Update Manager Notifications
      apt:
        name: update-manager
        state: absent
      tags: update-manager

    # Install Other Dependencies and Software
    - name: Installing Other Useful Software - This may take some time...Beer O'clock!
      apt:
        name: "{{ packages }}"
        state: present
        install_recommends: yes
      vars:
        packages:
          - apache2
          - apache2-bin
          - autoconf
          - automake
          - build-essential
          - cmake
          - cowsay
          - cowsay-off
          - cpanminus
          - filezilla
          - fortune-mod
          - gconf2
          - lolcat
          - m4
          - make
          - mosh
          - php7.2
          - python
          - python-pip
          - python3
          - python3-pip
          - sqlite3
          - tasksel
          - ubuntu-restricted-extras
          - unzip
          - uudeview
          - xcowsay
          - xvfb
          - zip
      tags: dependencies

    # Install X2Go
    - name: X2Go
      include: tasks/x2go.yaml
      tags: x2go

    # Install XRDP
    - name: XRDP
      include: tasks/xrdp.yaml
      tags: xrdp

    - name: MariaDB
      include: tasks/mariadb.yaml
      tags: mysql, mariadb

    - name: Open-Java and Oracle-Java
      include: tasks/java.yaml
      tags: java

    - name: Guacamole
      include: tasks/guacamole.yaml
      tags: guacamole

    - name: Google Chrome
      include: tasks/chrome.yaml
      tags: chrome
     
    - name: Installing Firefox
      apt:
        name: firefox
        state: present
        install_recommends: yes
      tags: firefox

    - name: Install R and R Studio Server/Dektop
      include: tasks/r_and_r_studio.yaml
      tags: r

    - name: profile stuff
      include: tasks/profile.yaml
      tags: alias, profile

    # Upgrade and Dist-Upgrade apt
    - name: Upgrade and Dist-Upgrade
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: full
      tags: upgrade